use_frameworks!

platform :ios, '8.0'

target 'TTC_Example' do
  pod 'TTC', :path => '../'

  target 'TTC_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
